In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
X = np.array([[1., -1., 2.],[2., 0., 0.],[0., 1., -1.]])

In [6]:
X_scaled = preprocessing.scale(X)

In [7]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
#The scaled data has 0 mean and a variance of 1
X_scaled.mean(axis=0)
X_scaled.std(axis=0)

array([ 1.,  1.,  1.])

In [12]:
#It is also possible to scale data  to a chosen range, usually between 0 and 1
#Take the array below and we will scale it to a matrix with range between 0 and 1 
X_train = np.array([[ 1., -1.,  2.],
                  [ 2.,  0.,  0.],
                  [ 0.,  1., -1.]])


In [13]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [14]:
X_train_minmax

array([[ 0.5       ,  0.        ,  1.        ],
       [ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  1.        ,  0.        ]])

In [15]:
#One of the most important reasons to do pre-processing is to encode features that are categorial,
#such as 'male', 'female' into integers. 

In [16]:
lbl = preprocessing.LabelEncoder()

In [26]:
cities = np.array(["london", "tokyo", "paris", "chennai", "chennai"])

In [27]:
lbl.fit(cities)

LabelEncoder()

In [28]:
list(lbl.classes_)

['chennai', 'london', 'paris', 'tokyo']

In [33]:
lbl.transform(cities).astype(int)

array([1, 3, 2, 0, 0])